config:
  m3o:accountId: b0a2804a399607a0f277e3d712983a00
  m3o:zoneId: 41191539f72c9a9d8b1596a71199c0ad
  m3o:environment: production
  m3o:contact-email: me@m3o.sh
  m3o:resume-url: https://github.com/marco-souza/resume/blob/main/RESUME_PDF.md
  # email
  m3o:emailMe: ma.souza.junior@gmail.com
  m3o:emailCatchAll: souza.marco@proton.me
  cloudflare:apiToken:
    secure: v1:jDceQw6c7TJQx7vb:u5ah9NkoPO/znVFJ3LSUBjsP1EvW8PmL6MYCL3hf5R0yolkOd2FQvpQRQyn44wF3vGkUd/VBldQ9MFpYtyobt34OricT
encryptionsalt: v1:iYqEeVVSP14=:v1:obQjSgTEEw9d8SxX:w4n+V2URB4TIoK2kIdSFvwDGSMJ4TQ==
