import { defineLiveCollection } from "astro:content";
import { z } from "astro/zod";

import { createIptvLoader } from "./lib/iptv/live-loader";

const iptvLoader = createIptvLoader();

/**
 * Zod schema for ChannelDTO entries.
 *
 * Validates every field served by the IPTV live loader.
 * Types are auto-generated by Astro from this schema — no manual interfaces.
 * NSFW channels are NOT filtered out here; filtering is left to the UI layer.
 */
const channelSchema = z.object({
  id: z.string(),
  name: z.string(),
  alt_names: z.array(z.string()),
  network: z.string().nullable(),
  country: z.string(),
  categories: z.array(z.string()),
  is_nsfw: z.boolean(),
  logo: z.string(),
  website: z.string().nullable(),
  streams: z.array(
    z.object({
      url: z.string(),
      quality: z.string().nullable(),
      format: z.string().nullable(),
      label: z.string().nullable(),
      referrer: z.string().nullable(),
      user_agent: z.string().nullable(),
    }),
  ),
});

export const collections = {
  channels: defineLiveCollection({
    type: "live",
    loader: iptvLoader,
    schema: channelSchema,
  }),
};
